sudo: false
language: ruby
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - 2.3.8
before_script:
  - gem install bundler -v '~> 2.0'
  - gem install rspec -v '~> 3.0'
  - gem install rubocop 
  - bundle
script:
  - bundle exec rspec
  - bundle exec rubocop
